name: chat_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 1.18.0
  google_sign_in: 5.3.3
  firebase_auth: 3.3.20
  lottie: 1.3.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/logo/
    - assets/models/
